# View Assist template sensor configuration
#
# You must set the following variables:
#  * name: Device name (eg ViewAssist-livingroom)
#  * unique_id:  Unique ID allows for editing in the UI, adding to areas, etc (eg viewassist_livingroom)
#  * icon: Sets an icon for the satellite (recommended mdi:glasses)
#  * type:  Used to determine a/v capabilities ("view_audio", "view_only", "audio_only". Default "view_audio")
#  * mic_device:  Used to assign microphone to View Assist device
#  * mediaplayer_device: Used to assign the media player used for View Assist text-to-speech playback
#  * musicplayer_device: Used to assign the media player used for View Assist music playback
#  * timer_device: Used to assign the timer helper device used for screen time outs
#  * display_device: Used to determine the correct Browser Mod instance to use for display
#  * browser_id: Used to assign the browser being used by Browsermod.  This will match the name you give the device in your Browsermod configuration
#
#
# Multiple sensors can be created by copy pasting the definition from the "- name" line until the end of
# the "timer_device" to the end of the template block and modifying with the next sensor details
# You must create a timer helper device per device
# You must create a sensor helper group (eg group.viewassist_satellites) and include all View Assist satellites in the group
#
# Example data included below.  This must be changed with your sensor values

template:
  - sensor:
    - name: ViewAssist-livingroom
      state: ""
      unique_id : "viewassist_livingroom"
      icon: "mdi:glasses"    
      attributes:
        type: view_audio
        mic_device: "sensor.streamassist-livingroom_stt"
        mediaplayer_device: "media_player.browsermod-livingroom"
        musicplayer_device: "media_player.browsermod-livingroom_2"
        display_device: "sensor.browsermod-livingroom_browser_path"
        browser_id: "ViewAssist-livingroom"
        timer_device: "timer.viewassist-livingroom"

        
