# View Assist - Tell Me a Joke(v 1.0.0)
blueprint:
  name: View Assist - Tell Me a Joke
  description: Ask Assist to tell you a joke and get ready to laugh or groan (View Assist tellmeajoke v 2.0.0)
  domain: automation
  input:
    command:
      name: Command 
      description: The phrase you want to use to trigger the joke request
      default: "tell [me | us] a joke"
     language:
      name: Language
      description: "Language code for the joke (supported: en, de, es, it, fr, gl, eu, ru)"
      default: "en"
alias: View Assist - Tell me a joke
description: ""
trigger:
  - platform: conversation
    command:
      - !input command
condition: []
action:
  - variables:
      target_satellite_device: "{{ view_assist_entity(trigger.device_id) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device')}}"
      target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type')}}"  
  - action: pyscript.viewassist_get_joke
    data:
      language: "{{ language }}"
  - set_conversation_response: "{{ joke_response['joke']  }}"
    enabled: true
mode: single
